#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Auction1")]
	public partial class OperationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBidUser(BidUser instance);
    partial void UpdateBidUser(BidUser instance);
    partial void DeleteBidUser(BidUser instance);
    partial void InsertMobil(Mobil instance);
    partial void UpdateMobil(Mobil instance);
    partial void DeleteMobil(Mobil instance);
    partial void InsertLoginUser(LoginUser instance);
    partial void UpdateLoginUser(LoginUser instance);
    partial void DeleteLoginUser(LoginUser instance);
    partial void InsertMerek(Merek instance);
    partial void UpdateMerek(Merek instance);
    partial void DeleteMerek(Merek instance);
    #endregion
		
		public OperationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Auction1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OperationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BidUser> BidUsers
		{
			get
			{
				return this.GetTable<BidUser>();
			}
		}
		
		public System.Data.Linq.Table<Mobil> Mobils
		{
			get
			{
				return this.GetTable<Mobil>();
			}
		}
		
		public System.Data.Linq.Table<LoginUser> LoginUsers
		{
			get
			{
				return this.GetTable<LoginUser>();
			}
		}
		
		public System.Data.Linq.Table<Merek> Mereks
		{
			get
			{
				return this.GetTable<Merek>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BidUser")]
	public partial class BidUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdKTP;
		
		private string _Nama;
		
		private string _Alamat;
		
		private string _Pekerjaan;
		
		private System.DateTime _TanggalBid;
		
		private System.DateTime _BatasBid;
		
		private decimal _Harga;
		
		private int _MerkId;
		
		private EntityRef<Merek> _Merek;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdKTPChanging(System.Nullable<int> value);
    partial void OnIdKTPChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnPekerjaanChanging(string value);
    partial void OnPekerjaanChanged();
    partial void OnTanggalBidChanging(System.DateTime value);
    partial void OnTanggalBidChanged();
    partial void OnBatasBidChanging(System.DateTime value);
    partial void OnBatasBidChanged();
    partial void OnHargaChanging(decimal value);
    partial void OnHargaChanged();
    partial void OnMerkIdChanging(int value);
    partial void OnMerkIdChanged();
    #endregion
		
		public BidUser()
		{
			this._Merek = default(EntityRef<Merek>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKTP", DbType="Int")]
		public System.Nullable<int> IdKTP
		{
			get
			{
				return this._IdKTP;
			}
			set
			{
				if ((this._IdKTP != value))
				{
					this.OnIdKTPChanging(value);
					this.SendPropertyChanging();
					this._IdKTP = value;
					this.SendPropertyChanged("IdKTP");
					this.OnIdKTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pekerjaan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pekerjaan
		{
			get
			{
				return this._Pekerjaan;
			}
			set
			{
				if ((this._Pekerjaan != value))
				{
					this.OnPekerjaanChanging(value);
					this.SendPropertyChanging();
					this._Pekerjaan = value;
					this.SendPropertyChanged("Pekerjaan");
					this.OnPekerjaanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalBid", DbType="Date NOT NULL")]
		public System.DateTime TanggalBid
		{
			get
			{
				return this._TanggalBid;
			}
			set
			{
				if ((this._TanggalBid != value))
				{
					this.OnTanggalBidChanging(value);
					this.SendPropertyChanging();
					this._TanggalBid = value;
					this.SendPropertyChanged("TanggalBid");
					this.OnTanggalBidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatasBid", DbType="Date NOT NULL")]
		public System.DateTime BatasBid
		{
			get
			{
				return this._BatasBid;
			}
			set
			{
				if ((this._BatasBid != value))
				{
					this.OnBatasBidChanging(value);
					this.SendPropertyChanging();
					this._BatasBid = value;
					this.SendPropertyChanged("BatasBid");
					this.OnBatasBidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga", DbType="Money NOT NULL")]
		public decimal Harga
		{
			get
			{
				return this._Harga;
			}
			set
			{
				if ((this._Harga != value))
				{
					this.OnHargaChanging(value);
					this.SendPropertyChanging();
					this._Harga = value;
					this.SendPropertyChanged("Harga");
					this.OnHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerkId", DbType="Int NOT NULL")]
		public int MerkId
		{
			get
			{
				return this._MerkId;
			}
			set
			{
				if ((this._MerkId != value))
				{
					if (this._Merek.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMerkIdChanging(value);
					this.SendPropertyChanging();
					this._MerkId = value;
					this.SendPropertyChanged("MerkId");
					this.OnMerkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merek_BidUser", Storage="_Merek", ThisKey="MerkId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Merek Merek
		{
			get
			{
				return this._Merek.Entity;
			}
			set
			{
				Merek previousValue = this._Merek.Entity;
				if (((previousValue != value) 
							|| (this._Merek.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Merek.Entity = null;
						previousValue.BidUsers.Remove(this);
					}
					this._Merek.Entity = value;
					if ((value != null))
					{
						value.BidUsers.Add(this);
						this._MerkId = value.Id;
					}
					else
					{
						this._MerkId = default(int);
					}
					this.SendPropertyChanged("Merek");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mobil")]
	public partial class Mobil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tahun;
		
		private string _Transmisi;
		
		private string _BBM;
		
		private string _NoPolisi;
		
		private System.DateTime _MasaBerlaku;
		
		private decimal _Harga;
		
		private int _MerkId;
		
		private EntityRef<Merek> _Merek;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTahunChanging(string value);
    partial void OnTahunChanged();
    partial void OnTransmisiChanging(string value);
    partial void OnTransmisiChanged();
    partial void OnBBMChanging(string value);
    partial void OnBBMChanged();
    partial void OnNoPolisiChanging(string value);
    partial void OnNoPolisiChanged();
    partial void OnMasaBerlakuChanging(System.DateTime value);
    partial void OnMasaBerlakuChanged();
    partial void OnHargaChanging(decimal value);
    partial void OnHargaChanged();
    partial void OnMerkIdChanging(int value);
    partial void OnMerkIdChanged();
    #endregion
		
		public Mobil()
		{
			this._Merek = default(EntityRef<Merek>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tahun", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tahun
		{
			get
			{
				return this._Tahun;
			}
			set
			{
				if ((this._Tahun != value))
				{
					this.OnTahunChanging(value);
					this.SendPropertyChanging();
					this._Tahun = value;
					this.SendPropertyChanged("Tahun");
					this.OnTahunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transmisi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Transmisi
		{
			get
			{
				return this._Transmisi;
			}
			set
			{
				if ((this._Transmisi != value))
				{
					this.OnTransmisiChanging(value);
					this.SendPropertyChanging();
					this._Transmisi = value;
					this.SendPropertyChanged("Transmisi");
					this.OnTransmisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BBM
		{
			get
			{
				return this._BBM;
			}
			set
			{
				if ((this._BBM != value))
				{
					this.OnBBMChanging(value);
					this.SendPropertyChanging();
					this._BBM = value;
					this.SendPropertyChanged("BBM");
					this.OnBBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoPolisi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NoPolisi
		{
			get
			{
				return this._NoPolisi;
			}
			set
			{
				if ((this._NoPolisi != value))
				{
					this.OnNoPolisiChanging(value);
					this.SendPropertyChanging();
					this._NoPolisi = value;
					this.SendPropertyChanged("NoPolisi");
					this.OnNoPolisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasaBerlaku", DbType="Date NOT NULL")]
		public System.DateTime MasaBerlaku
		{
			get
			{
				return this._MasaBerlaku;
			}
			set
			{
				if ((this._MasaBerlaku != value))
				{
					this.OnMasaBerlakuChanging(value);
					this.SendPropertyChanging();
					this._MasaBerlaku = value;
					this.SendPropertyChanged("MasaBerlaku");
					this.OnMasaBerlakuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga", DbType="Money NOT NULL")]
		public decimal Harga
		{
			get
			{
				return this._Harga;
			}
			set
			{
				if ((this._Harga != value))
				{
					this.OnHargaChanging(value);
					this.SendPropertyChanging();
					this._Harga = value;
					this.SendPropertyChanged("Harga");
					this.OnHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerkId", DbType="Int NOT NULL")]
		public int MerkId
		{
			get
			{
				return this._MerkId;
			}
			set
			{
				if ((this._MerkId != value))
				{
					if (this._Merek.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMerkIdChanging(value);
					this.SendPropertyChanging();
					this._MerkId = value;
					this.SendPropertyChanged("MerkId");
					this.OnMerkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merek_Mobil", Storage="_Merek", ThisKey="MerkId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Merek Merek
		{
			get
			{
				return this._Merek.Entity;
			}
			set
			{
				Merek previousValue = this._Merek.Entity;
				if (((previousValue != value) 
							|| (this._Merek.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Merek.Entity = null;
						previousValue.Mobils.Remove(this);
					}
					this._Merek.Entity = value;
					if ((value != null))
					{
						value.Mobils.Add(this);
						this._MerkId = value.Id;
					}
					else
					{
						this._MerkId = default(int);
					}
					this.SendPropertyChanged("Merek");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoginUser")]
	public partial class LoginUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nama;
		
		private string _Alamat;
		
		private string _Pswd;
		
		private string _Email;
		
		private int _IdKTP;
		
		private string _Pekerjaan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnPswdChanging(string value);
    partial void OnPswdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIdKTPChanging(int value);
    partial void OnIdKTPChanged();
    partial void OnPekerjaanChanging(string value);
    partial void OnPekerjaanChanged();
    #endregion
		
		public LoginUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pswd", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Pswd
		{
			get
			{
				return this._Pswd;
			}
			set
			{
				if ((this._Pswd != value))
				{
					this.OnPswdChanging(value);
					this.SendPropertyChanging();
					this._Pswd = value;
					this.SendPropertyChanged("Pswd");
					this.OnPswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKTP", DbType="Int NOT NULL")]
		public int IdKTP
		{
			get
			{
				return this._IdKTP;
			}
			set
			{
				if ((this._IdKTP != value))
				{
					this.OnIdKTPChanging(value);
					this.SendPropertyChanging();
					this._IdKTP = value;
					this.SendPropertyChanged("IdKTP");
					this.OnIdKTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pekerjaan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pekerjaan
		{
			get
			{
				return this._Pekerjaan;
			}
			set
			{
				if ((this._Pekerjaan != value))
				{
					this.OnPekerjaanChanging(value);
					this.SendPropertyChanging();
					this._Pekerjaan = value;
					this.SendPropertyChanged("Pekerjaan");
					this.OnPekerjaanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Merek")]
	public partial class Merek : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NamaMobil;
		
		private EntitySet<BidUser> _BidUsers;
		
		private EntitySet<Mobil> _Mobils;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNamaMobilChanging(string value);
    partial void OnNamaMobilChanged();
    #endregion
		
		public Merek()
		{
			this._BidUsers = new EntitySet<BidUser>(new Action<BidUser>(this.attach_BidUsers), new Action<BidUser>(this.detach_BidUsers));
			this._Mobils = new EntitySet<Mobil>(new Action<Mobil>(this.attach_Mobils), new Action<Mobil>(this.detach_Mobils));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaMobil", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NamaMobil
		{
			get
			{
				return this._NamaMobil;
			}
			set
			{
				if ((this._NamaMobil != value))
				{
					this.OnNamaMobilChanging(value);
					this.SendPropertyChanging();
					this._NamaMobil = value;
					this.SendPropertyChanged("NamaMobil");
					this.OnNamaMobilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merek_BidUser", Storage="_BidUsers", ThisKey="Id", OtherKey="MerkId")]
		public EntitySet<BidUser> BidUsers
		{
			get
			{
				return this._BidUsers;
			}
			set
			{
				this._BidUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merek_Mobil", Storage="_Mobils", ThisKey="Id", OtherKey="MerkId")]
		public EntitySet<Mobil> Mobils
		{
			get
			{
				return this._Mobils;
			}
			set
			{
				this._Mobils.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BidUsers(BidUser entity)
		{
			this.SendPropertyChanging();
			entity.Merek = this;
		}
		
		private void detach_BidUsers(BidUser entity)
		{
			this.SendPropertyChanging();
			entity.Merek = null;
		}
		
		private void attach_Mobils(Mobil entity)
		{
			this.SendPropertyChanging();
			entity.Merek = this;
		}
		
		private void detach_Mobils(Mobil entity)
		{
			this.SendPropertyChanging();
			entity.Merek = null;
		}
	}
}
#pragma warning restore 1591
